# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: setlistfm
  description: ðŸ”Œ Setlist.fm webservice client for php.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, php, library, setlistfm, setlist, api, webservice-client

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (8.0)"
          - "Static Code Analysis (8.1)"
          - "Test (PHP 8, lowest)"
          - "Test (PHP 8, highest)"
          - "Test (PHP 8.1, lowest)"
          - "Test (PHP 8.1, highest)"
          - "Code Coverage (8.1)"
          - "Mutation Tests (8.1)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
